<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>practicafinal_najli_yaya_estevez</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="PracticaFinal_Najli_Yaya_Estevez_files/libs/clipboard/clipboard.min.js"></script>
<script src="PracticaFinal_Najli_Yaya_Estevez_files/libs/quarto-html/quarto.js"></script>
<script src="PracticaFinal_Najli_Yaya_Estevez_files/libs/quarto-html/popper.min.js"></script>
<script src="PracticaFinal_Najli_Yaya_Estevez_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="PracticaFinal_Najli_Yaya_Estevez_files/libs/quarto-html/anchor.min.js"></script>
<link href="PracticaFinal_Najli_Yaya_Estevez_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="PracticaFinal_Najli_Yaya_Estevez_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="PracticaFinal_Najli_Yaya_Estevez_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="PracticaFinal_Najli_Yaya_Estevez_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="PracticaFinal_Najli_Yaya_Estevez_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">



<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
</div>
<p>Cargar los datos en un dataframe llamado: airbnb</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>airbnb<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">'data//airbnb.csv'</span>,<span class="at">sep =</span> <span class="st">','</span>, <span class="at">stringsAsFactors =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Mostrar las primeras 6 filas del dataframe</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airbnb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Zipcode Neighbourhood.Cleansed Property.Type       Room.Type Accommodates
1   28004            Universidad     Apartment    Private room            2
2   28004            Universidad     Apartment Entire home/apt            6
3   28004            Universidad     Apartment Entire home/apt            3
4   28004            Universidad          Loft Entire home/apt            3
5   28015            Universidad     Apartment Entire home/apt            5
6   28004            Universidad     Apartment Entire home/apt            2
  Bathrooms Bedrooms Beds Bed.Type
1         2        1    1 Real Bed
2         1        3    5 Real Bed
3         1        2    2 Real Bed
4         2        1    1 Real Bed
5         1        1    1 Real Bed
6         1        0    1 Real Bed
                                                                                                                                                                                                                                                                                                                                                         Amenities
1                                                                                                                                                                              TV,Wireless Internet,Kitchen,Pets allowed,Pets live on this property,Buzzer/wireless intercom,Heating,Suitable for events,Washer,First aid kit,Essentials,Lock on bedroom door,Iron
2                                                                                                                                                                                      TV,Internet,Wireless Internet,Air conditioning,Kitchen,Indoor fireplace,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,Essentials,Shampoo
3                                                                                                                                                                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Doorman,Heating,Family/kid friendly,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace
4                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Pets allowed,Breakfast,Elevator in building,Indoor fireplace,Buzzer/wireless intercom,Heating,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace,translation missing: en.hosting_amenity_49,translation missing: en.hosting_amenity_50
5                                                                                                                                                                                                               TV,Wireless Internet,Air conditioning,Kitchen,Smoking allowed,Pets allowed,Elevator in building,Heating,Family/kid friendly,Washer,Essentials,Iron
6 TV,Cable TV,Internet,Wireless Internet,Air conditioning,Wheelchair accessible,Kitchen,Doorman,Elevator in building,Buzzer/wireless intercom,Heating,Washer,Smoke detector,Carbon monoxide detector,First aid kit,Safety card,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace,Self Check-In,Doorman Entry
  Square.Feet Price Review.Scores.Rating
1          NA    35                   NA
2          NA    92                   96
3          NA    55                   91
4          NA    60                  100
5         538    75                   90
6          NA    55                   95</code></pre>
</div>
</div>
<p>Renombrar las columnas de la siguiente forma:</p>
<table class="table">
<thead>
<tr class="header">
<th>Nombre original</th>
<th>Nuevo nombre</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Zipcode</td>
<td>CodigoPostal</td>
</tr>
<tr class="even">
<td>Neighbourhood.Cleansed</td>
<td>Barrio</td>
</tr>
<tr class="odd">
<td>Property.Type</td>
<td>TipoPropiedad</td>
</tr>
<tr class="even">
<td>Room.Type</td>
<td>TipoAlquiler</td>
</tr>
<tr class="odd">
<td>Accommodates</td>
<td>MaxOcupantes</td>
</tr>
<tr class="even">
<td>Bathrooms</td>
<td>NumBanyos</td>
</tr>
<tr class="odd">
<td>Bedrooms</td>
<td>NumDormitorios</td>
</tr>
<tr class="even">
<td>Beds</td>
<td>NumCamas</td>
</tr>
<tr class="odd">
<td>Bed.Type</td>
<td>TipoCama</td>
</tr>
<tr class="even">
<td>Amenities</td>
<td>Comodidades</td>
</tr>
<tr class="odd">
<td>Square.Feet</td>
<td>PiesCuadrados</td>
</tr>
<tr class="even">
<td>Price</td>
<td>Precio</td>
</tr>
<tr class="odd">
<td>Review.Scores.Rating</td>
<td>Puntuacion</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(airbnb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Zipcode"                "Neighbourhood.Cleansed" "Property.Type"         
 [4] "Room.Type"              "Accommodates"           "Bathrooms"             
 [7] "Bedrooms"               "Beds"                   "Bed.Type"              
[10] "Amenities"              "Square.Feet"            "Price"                 
[13] "Review.Scores.Rating"  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(airbnb) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"CodigoPostal"</span>,<span class="st">"Barrio"</span>,<span class="st">"TipoPropiedad"</span>,<span class="st">"TipoAlquiler"</span>,<span class="st">"MaxOcupantes"</span>,<span class="st">"NumBanyos"</span>,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="st">"NumDormitorios"</span>,<span class="st">"NumCamas"</span>,<span class="st">"TipoCama"</span>,<span class="st">"Comodidades"</span>,<span class="st">"PiesCuadrados"</span>,<span class="st">"Precio"</span>,<span class="st">"Puntuacion"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airbnb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  CodigoPostal      Barrio TipoPropiedad    TipoAlquiler MaxOcupantes NumBanyos
1        28004 Universidad     Apartment    Private room            2         2
2        28004 Universidad     Apartment Entire home/apt            6         1
3        28004 Universidad     Apartment Entire home/apt            3         1
4        28004 Universidad          Loft Entire home/apt            3         2
5        28015 Universidad     Apartment Entire home/apt            5         1
6        28004 Universidad     Apartment Entire home/apt            2         1
  NumDormitorios NumCamas TipoCama
1              1        1 Real Bed
2              3        5 Real Bed
3              2        2 Real Bed
4              1        1 Real Bed
5              1        1 Real Bed
6              0        1 Real Bed
                                                                                                                                                                                                                                                                                                                                                       Comodidades
1                                                                                                                                                                              TV,Wireless Internet,Kitchen,Pets allowed,Pets live on this property,Buzzer/wireless intercom,Heating,Suitable for events,Washer,First aid kit,Essentials,Lock on bedroom door,Iron
2                                                                                                                                                                                      TV,Internet,Wireless Internet,Air conditioning,Kitchen,Indoor fireplace,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,Essentials,Shampoo
3                                                                                                                                                                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Doorman,Heating,Family/kid friendly,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace
4                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Pets allowed,Breakfast,Elevator in building,Indoor fireplace,Buzzer/wireless intercom,Heating,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace,translation missing: en.hosting_amenity_49,translation missing: en.hosting_amenity_50
5                                                                                                                                                                                                               TV,Wireless Internet,Air conditioning,Kitchen,Smoking allowed,Pets allowed,Elevator in building,Heating,Family/kid friendly,Washer,Essentials,Iron
6 TV,Cable TV,Internet,Wireless Internet,Air conditioning,Wheelchair accessible,Kitchen,Doorman,Elevator in building,Buzzer/wireless intercom,Heating,Washer,Smoke detector,Carbon monoxide detector,First aid kit,Safety card,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace,Self Check-In,Doorman Entry
  PiesCuadrados Precio Puntuacion
1            NA     35         NA
2            NA     92         96
3            NA     55         91
4            NA     60        100
5           538     75         90
6            NA     55         95</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#newnames&lt;-c("CodigoPostal","Barrio","TipoPropiedad","TipoAlquiler","MaxOcupantes","NumBanyos",</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co">#"NumDormitorios","NumCamas","TipoCama","Comodidades","PiesCuadrados","Precio","Puntuacion")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Crea una nueva columna llamada MetrosCuadrados a partir de la columna PiesCuadrados.</p>
<p>Ayuda: 1 pie cuadrado son 0,092903 metros cuadrados</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="st">"MetrosCuadrados"</span>] <span class="ot">&lt;-</span> airbnb<span class="sc">$</span>PiesCuadrados <span class="sc">*</span> <span class="fl">0.092903</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airbnb<span class="sc">$</span>PiesCuadrados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  NA  NA  NA  NA 538  NA</code></pre>
</div>
</div>
<p>Miremos el código postal. Es una variable con entradas erroneas. Hay valores como ’‘,’-’ y ‘28’ que deberían ser considerados como NA. Así mismo también debería ser NA todos los que no comiencen por 28, ya que estamos con códigos postales de Madrid</p>
<p>El código postal 28002, 28004 y 28051 tienen entradas repetidas. Por ejemplo las entradas 28002 deberían ir dentro de 28002</p>
<p>El codigo 2804 debería ser 28004, 2805 deberia ser 28005 y 2815 junto con 2815 debería ser 28015</p>
<p>Limpia los datos de la columna Codigo Postal</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">","</span>),<span class="st">"CodigoPostal"</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">"-"</span>),<span class="st">"CodigoPostal"</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">"28"</span>),<span class="st">"CodigoPostal"</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">""</span>),<span class="st">"CodigoPostal"</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">"28002</span><span class="sc">\n</span><span class="st">28002"</span>),<span class="st">"CodigoPostal"</span>] <span class="ot">&lt;-</span> <span class="st">"28002"</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">"28051</span><span class="sc">\n</span><span class="st">28051"</span>), <span class="st">"CodigoPostal"</span>] <span class="ot">&lt;-</span><span class="st">"28051"</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">"Madrid 28004"</span>), <span class="st">"CodigoPostal"</span>] <span class="ot">&lt;-</span> <span class="st">"28004"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">"2804"</span>),<span class="st">"CodigoPostal"</span>] <span class="ot">&lt;-</span> <span class="st">"28004"</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">"2805"</span>),<span class="st">"CodigoPostal"</span>] <span class="ot">&lt;-</span> <span class="st">"28005"</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">"2815"</span>),<span class="st">"CodigoPostal"</span>] <span class="ot">&lt;-</span> <span class="st">"28015"</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">"2015"</span>),<span class="st">"CodigoPostal"</span>] <span class="ot">&lt;-</span> <span class="st">"28015"</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">"280013"</span>), <span class="st">"CodigoPostal"</span>] <span class="ot">&lt;-</span> <span class="st">"28013"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Una vez limpios los datos ¿Cuales son los códigos postales que tenemos?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># La columna CodigoPostal estaba como de tipo factor, primero tenemos que quitar los valores "levels" vacíos</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal <span class="ot">&lt;-</span> <span class="fu">droplevels</span>(airbnb<span class="sc">$</span>CodigoPostal)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(airbnb<span class="sc">$</span>CodigoPostal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
20013 20126 25008 27004 27013 28001 28002 28003 28004 28005 28006 28007 28008 
    1     1     1     1     1   231   171   185  1796  1195   218   206   338 
28009 28010 28011 28012 28013 28014 28015 28016 28017 28018 28019 28020 28021 
  216   384   250  2060  1020   630   602    76   107    43   200   192    58 
28022 28023 28024 28025 28026 28027 28028 28029 28030 28031 28032 28033 28034 
   30    23    44   123    93   122   263   110    73    27    33    89    45 
28035 28036 28037 28038 28039 28040 28041 28042 28043 28044 28045 28046 28047 
   59    67    65    77   160    16    63    90   103    19   495    32    67 
28048 28049 28050 28051 28052 28053 28054 28055 28056 28058 28060 28094 28105 
    1     3    58    17     1    85    12    12     1     1     1     1     1 
28850 
    1 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(airbnb<span class="sc">$</span>CodigoPostal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "20013" "20126" "25008" "27004" "27013" "28001" "28002" "28003" "28004"
[10] "28005" "28006" "28007" "28008" "28009" "28010" "28011" "28012" "28013"
[19] "28014" "28015" "28016" "28017" "28018" "28019" "28020" "28021" "28022"
[28] "28023" "28024" "28025" "28026" "28027" "28028" "28029" "28030" "28031"
[37] "28032" "28033" "28034" "28035" "28036" "28037" "28038" "28039" "28040"
[46] "28041" "28042" "28043" "28044" "28045" "28046" "28047" "28048" "28049"
[55] "28050" "28051" "28052" "28053" "28054" "28055" "28056" "28058" "28060"
[64] "28094" "28105" "28850"</code></pre>
</div>
</div>
<p>¿Cuales son los 5 códigos postales con más entradas? ¿Y con menos? ¿Cuantas entradas tienen?</p>
<p><em>Los 5 Códigos Postales con más entradas son:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">sort</span>(<span class="fu">table</span>(airbnb<span class="sc">$</span>CodigoPostal),<span class="at">decreasing =</span> <span class="cn">TRUE</span>),<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
28012 28004 28005 28013 28014 
 2060  1796  1195  1020   630 </code></pre>
</div>
</div>
<p><em>Los 5 Códigos Postales con menos entradas son:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">sort</span>(<span class="fu">table</span>(airbnb<span class="sc">$</span>CodigoPostal)),<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
20013 20126 25008 27004 27013 
    1     1     1     1     1 </code></pre>
</div>
</div>
<p>¿Cuales son los barrios que hay en el código postal 28012?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>airbnb_28012 <span class="ot">&lt;-</span> airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">'28012'</span>),]</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>airbnb_28012 <span class="ot">&lt;-</span> airbnb_28012[,<span class="fu">c</span>(<span class="st">"CodigoPostal"</span>, <span class="st">"Barrio"</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>Los barrios con CP: 28012 son Embajadores, Sol, Cortes, Palos de Moguer, Palacio y Acacias</em></p>
<p>¿Cuantas entradas hay en cada uno de esos barrios para el codigo postal 28012?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(airbnb_28012)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  CodigoPostal              Barrio    
 28012  :2060   Embajadores    :1449  
 20013  :   0   Sol            : 301  
 20126  :   0   Cortes         : 216  
 25008  :   0   Palos de Moguer:  46  
 27004  :   0   Palacio        :  27  
 27013  :   0   Acacias        :  13  
 (Other):   0   (Other)        :   8  </code></pre>
</div>
</div>
<p><em>Embajadores: 1449; Sol: 301; Cortes: 216; Palos de Moguer: 46; Palacio: 27 y Acacias: 13</em></p>
<p>¿Cuantos barrios hay en todo el dataset airbnb? ¿Cuales son?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(airbnb<span class="sc">$</span>Barrio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                    Abrantes                      Acacias 
                          18                          145 
                     Adelfas                   Aeropuerto 
                          51                            6 
                     Aguilas             Alameda de Osuna 
                          15                           24 
                     Almagro                     Almenara 
                         155                           62 
                 Almendrales                       Aluche 
                          45                           45 
                      Ambroz                      Amposta 
                          12                            5 
            Apostol Santiago                     Arapiles 
                          15                          182 
                     Aravaca                        Arcos 
                          16                           18 
                   Argüelles                       Atocha 
                         264                           18 
               Bellas Vistas                   Berruguete 
                          79                           67 
                  Buenavista                     Butarque 
                          22                            6 
                  Campamento                     Canillas 
                          22                           42 
                  Canillejas                     Cármenes 
                           7                           30 
               Casa de Campo   Casco Histórico de Barajas 
                          75                           28 
 Casco Histórico de Vallecas Casco Histórico de Vicálvaro 
                          40                           20 
                  Castellana                     Castilla 
                          97                           26 
                 Castillejos                      Chopera 
                          81                          112 
               Ciudad Jardín         Ciudad Universitaria 
                          55                           34 
                      Colina                     Comillas 
                          16                           59 
                  Concepción                   Corralejos 
                          46                            5 
                      Cortes                  Costillares 
                         750                           32 
              Cuatro Caminos               Cuatro Vientos 
                         120                            3 
                    Delicias                    El Goloso 
                         126                            3 
                  El Plantío                      El Viso 
                           3                           45 
                 Embajadores                    Entrevías 
                        1844                           13 
                    Estrella                    Fontarrón 
                          28                           24 
            Fuente del Berro                Fuentelareina 
                          68                            3 
                  Gaztambide                         Goya 
                         142                          229 
                  Guindalera                       Hellín 
                         187                            5 
              Hispanoamérica                        Ibiza 
                          72                          105 
                    Imperial                    Jerónimos 
                          89                           90 
                    Justicia                       La Paz 
                         785                           16 
                     Legazpi                        Lista 
                          37                          129 
                 Los Angeles                  Los Rosales 
                          16                           28 
                      Lucero                   Marroquina 
                          62                           12 
                 Media Legua                   Mirasierra 
                          17                           18 
                    Moscardó                   Niño Jesús 
                          34                           26 
                Nueva España                     Numancia 
                          60                           58 
                      Opañel                    Orcasitas 
                          57                            2 
                     Orcasur                     Pacífico 
                           8                          138 
                     Palacio                      Palomas 
                        1083                           12 
             Palomeras Bajas            Palomeras Sureste 
                          33                           15 
             Palos de Moguer                      Pavones 
                         262                            4 
                  Peñagrande                        Pilar 
                          39                           26 
               Pinar del Rey                      Piovera 
                          47                           12 
                    Portazgo                   Pradolongo 
                          19                           14 
                 Prosperidad                 Pueblo Nuevo 
                          98                           41 
               Puerta Bonita             Puerta del Angel 
                          38                          199 
                    Quintana                    Recoletos 
                          45                          172 
                       Rejas                   Rios Rosas 
                          20                          104 
                       Rosas                     Salvador 
                           4                           13 
                  San Andrés                San Cristobal 
                          21                            8 
                   San Diego                   San Fermín 
                          80                           32 
                  San Isidro            San Juan Bautista 
                          85                           26 
                 San Pascual                Santa Eugenia 
                          18                            4 
                    Simancas                          Sol 
                          45                          940 
                       Timón                    Trafalgar 
                          16                          315 
                 Universidad                Valdeacederas 
                        1358                           48 
                Valdefuentes                   Valdemarín 
                          55                            4 
                  Valdezarza                 Vallehermoso 
                          20                           60 
                    Valverde                       Ventas 
                          45                           78 
                   Vinateros                 Vista Alegre 
                          17                           74 
                       Zofío 
                           9 </code></pre>
</div>
</div>
<p>¿Cuales son los 5 barrios que tienen mayor número de entradas?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">sort</span>(<span class="fu">table</span>(airbnb<span class="sc">$</span>Barrio), <span class="at">decreasing=</span><span class="cn">TRUE</span>), <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Embajadores Universidad     Palacio         Sol    Justicia 
       1844        1358        1083         940         785 </code></pre>
</div>
</div>
<p><em>Los barrios son Embajadores (1844 entradas), Universidad (1358 entradas), Palacio (1083 entradas), Sol (940 entradas) y Justicia (785 entradas)</em></p>
<p>¿Cuantos Tipos de Alquiler diferentes hay? ¿Cuales son? ¿Cuantas entradas en el dataframe hay por cada tipo?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(airbnb<span class="sc">$</span>TipoAlquiler)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Entire home/apt    Private room     Shared room 
           7903            5113             191 </code></pre>
</div>
</div>
<p><em>Hay 3 tipos de alquiler: Entire home/apt (7903 entradas), Private room (5113 entradas) y Shared room (191 entradas)</em></p>
<p>Muestra el diagrama de cajas (boxplot) del precio para cada uno de los diferentes Tipos de Alquiler</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>airbnb, <span class="fu">aes</span>(<span class="at">x=</span>TipoAlquiler ,<span class="at">y=</span>Precio, <span class="at">color=</span>TipoAlquiler))<span class="sc">+</span><span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 9 rows containing non-finite values (`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="PracticaFinal_Najli_Yaya_Estevez_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>¿Cual es el precio medio de alquiler de cada Tipo de Alquiler?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>TipoAlquiler<span class="sc">==</span><span class="st">'Entire home/apt'</span>),]</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>TipoAlquiler<span class="sc">==</span><span class="st">'Private room'</span>),]</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>df3 <span class="ot">&lt;-</span> airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>TipoAlquiler<span class="sc">==</span><span class="st">'Shared room'</span>),]</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>pmedio_entire <span class="ot">&lt;-</span> <span class="fu">mean</span>(df1<span class="sc">$</span>Precio, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>pmedio_private <span class="ot">&lt;-</span> <span class="fu">mean</span>(df2<span class="sc">$</span>Precio, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>pmedio_shared <span class="ot">&lt;-</span> <span class="fu">mean</span>(df3<span class="sc">$</span>Precio, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Precio medio piso entero: "</span>,pmedio_entire)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Precio medio piso entero:  87.2966058763931"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Precio medio habitacion privada: "</span>, pmedio_private)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Precio medio habitacion privada:  34.255135981217"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Precio medio habitacion compartida: "</span>, pmedio_shared)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Precio medio habitacion compartida:  29.8534031413613"</code></pre>
</div>
</div>
<p><em>Precio medio piso entero: 87.2966058763931</em></p>
<p><em>Precio medio habitacion privada: 34.255135981217</em></p>
<p><em>Precio medio habitacion compartida: 29.8534031413613</em></p>
<p>La diferencia de precio medio para los tipo de alquiler, ¿es estadísticamente significativa? ¿Con que test lo comprobarías?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Primero comprobamos si siguen distribucion gaussiana con el test de Shapiro</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="co"># El test te Shapiro limita las filas a 5000,así que hay que coger los 5000 primeros registros de Entire home/apt y de Private room</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>df_entire <span class="ot">&lt;-</span> airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>TipoAlquiler <span class="sc">==</span> <span class="st">'Entire home/apt'</span>),]</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>df_entire <span class="ot">&lt;-</span> df_entire[<span class="dv">1</span><span class="sc">:</span><span class="dv">5000</span>,]</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>df_private <span class="ot">&lt;-</span> airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>TipoAlquiler <span class="sc">==</span> <span class="st">'Private room'</span>),]</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>df_private <span class="ot">&lt;-</span> df_private[<span class="dv">1</span><span class="sc">:</span><span class="dv">5000</span>,]</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Para test de Shapiro, la H0 es que sigue una distribución gaussiana...</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Las muestras de precio para pisos completos parecen seguir una gaussiana. pvalor:"</span>,</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>          <span class="fu">shapiro.test</span>(df_entire<span class="sc">$</span>Precio)<span class="sc">$</span>p.value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Las muestras de precio para pisos completos parecen seguir una gaussiana. pvalor: 1.24077898621874e-72"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Las muestras de precio para pisos con habitacion privada parecen seguir una gaussiana. pvalor:"</span>,</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>          <span class="fu">shapiro.test</span>(df_private<span class="sc">$</span>Precio)<span class="sc">$</span>p.value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Las muestras de precio para pisos con habitacion privada parecen seguir una gaussiana. pvalor: 9.18974842339072e-85"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Las muestras de precio para pisos con habitacion compartida parecen seguir una gaussiana. pvalor:"</span>,</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>          <span class="fu">shapiro.test</span>(airbnb<span class="sc">$</span>Precio[airbnb<span class="sc">$</span>TipoAlquiler<span class="sc">==</span><span class="st">'Shared room'</span>])<span class="sc">$</span>p.value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Las muestras de precio para pisos con habitacion compartida parecen seguir una gaussiana. pvalor: 4.51672121600842e-24"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Han salido todos los p-valor MUY pequeños, así que NO siguen distr.gaussiana</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>p-valor muy pequeño, &lt;0.05, luego NO son gaussianas así que hacemos Kruskal-Wallis para 3 grupos que no siguen distr gaussiana:</em></p>
<p><em>Hipótesis H0 Kruskal: las medias son iguales, la diferencia de precio entre los tipos de alquiler NO es estadísticamente significativa,</em></p>
<p><em>Hipótesis H1 Kruskal: la diferencia de precio entre los tipos de alquiler es estadísticamente significativa</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>( Precio <span class="sc">~</span> TipoAlquiler, <span class="at">data=</span>airbnb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  Precio by TipoAlquiler
Kruskal-Wallis chi-squared = 7235.6, df = 2, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p><em>El p-valor es muy pequeño así que descartamos la hipótesis nula y diremos que parece que hay diferencia de precio entre los tipos de alquiler y que es estadísticamente significativa</em></p>
<p>Filtra el dataframe cuyos tipo de alquiler sea ‘Entire home/apt’ y guardalo en un dataframe llamado <em>airbnb_entire</em>. Estas serán las entradas que tienen un alquiler del piso completo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>airbnb_entire <span class="ot">&lt;-</span> airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>TipoAlquiler<span class="sc">==</span><span class="st">'Entire home/apt'</span>),]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>¿Cuales son los 5 barrios que tienen un mayor número de apartamentos enteros en alquiler? Nota: Mirar solo en airbnb_entire. A partir de este punto y hasta que se diga lo contrario partiremos de airbnb_entire.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">sort</span>(<span class="fu">table</span>(airbnb_entire<span class="sc">$</span>Barrio), <span class="at">decreasing=</span><span class="cn">TRUE</span>),<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Embajadores Universidad     Palacio         Sol      Cortes 
       1228         984         769         701         574 </code></pre>
</div>
</div>
<p><em>Los barrios con más pisos en alquiler son, en orden decreciente de nº de apartamentos: Embajadores, Universidad, Palacio, Sol y Cortes</em></p>
<p>¿Cuales son los 5 barrios que tienen un mayor precio medio de alquiler para apartamentos enteros (es decir, del dataframe airbnb_entire)? ¿Cual es su precio medio? Ayuda: Usa la función aggregate <code>aggregate(.~colname,df,mean,na.rm=TRUE)</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>top_precio <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(airbnb_entire<span class="sc">$</span>Precio , <span class="fu">list</span>(airbnb_entire<span class="sc">$</span>Barrio), <span class="at">FUN=</span>mean, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(top_precio) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Barrio"</span>, <span class="st">"PrecioMedio"</span>)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Ordeno de mayor a menor precio medio</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>top5_precio <span class="ot">&lt;-</span> top_precio[<span class="fu">with</span>(top_precio, <span class="fu">order</span>(<span class="sc">-</span>top_precio<span class="sc">$</span>PrecioMedio)),]</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(top5_precio,<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Barrio PrecioMedio
77       Palomas    309.7500
50 Fuentelareina    180.0000
93     Recoletos    161.9254
43    El Plantío    150.0000
30    Castellana    141.3889</code></pre>
</div>
</div>
<p><em>Los 5 barrios con mayor precio medio de alquiler son (en orden decreciente de precio medio): Palomas, Fuentelareina, Recoletos, El Plantío y Castellana</em></p>
<p>¿Cuantos apartamentos hay en cada uno de esos barrios? Mostrar un dataframe con el nombre del barrio, el precio y el número de entradas. Ayuda: Podeis crear un nuevo dataframe con las columnas “Barrio” y “Freq” que contenga el número de entradas en cada barrio y hacer un merge con el dataframe del punto anterior.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Crear un df con columna de Barrio y un count de cuántas entradas tiene ese barrio</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>df_aux <span class="ot">&lt;-</span> airbnb_entire <span class="sc">|&gt;</span> <span class="fu">group_by</span>(Barrio) <span class="sc">|&gt;</span> <span class="fu">count</span>()</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df_aux)[<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="st">'CtdadPisos'</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>                                              </span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Luego hago un merge con el df top_precio, que tiene los campos Barrio y PrecioMedio</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>airbnb_mini <span class="ot">&lt;-</span> <span class="fu">merge</span>(df_aux, top_precio)</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Ahora respondo a la pregunta: "¿Cuantos apartamentos hay en cada uno de esos barrios(los de mayor precio medio)?"</span></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>top5_precio_apt <span class="ot">&lt;-</span> airbnb_mini[<span class="fu">with</span>(airbnb_mini, <span class="fu">order</span>(<span class="sc">-</span>airbnb_mini<span class="sc">$</span>PrecioMedio)),]</span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(top5_precio_apt,<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Barrio CtdadPisos PrecioMedio
77       Palomas          4    309.7500
50 Fuentelareina          2    180.0000
93     Recoletos        135    161.9254
43    El Plantío          1    150.0000
30    Castellana         73    141.3889</code></pre>
</div>
</div>
<p><em>El número de apartamentos en cada barrio son: Palomas -&gt; 4; Fuentelareina -&gt; 2; Recoletos -&gt; 135; El Plantío -&gt; 1; Castellana -&gt; 73</em></p>
<p>Partiendo del dataframe anterior, muestra los 5 barrios con mayor precio, pero que tengan más de 100 entradas de alquiler.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>top5_precio_100 <span class="ot">&lt;-</span> top5_precio_apt[<span class="fu">which</span>(top5_precio_apt<span class="sc">$</span>CtdadPisos <span class="sc">&gt;</span> <span class="dv">100</span> ),]</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(top5_precio_100, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Barrio CtdadPisos PrecioMedio
93  Recoletos        135   161.92537
52       Goya        142   111.33803
106       Sol        701   100.75036
108 Trafalgar        223    98.57848
59   Justicia        534    98.25468</code></pre>
</div>
</div>
<p><em>En este caso, los 5 barrios con mayor precio medio y con más de 100 pisos en alquiler son: Recoletos, Goya, Sol, Trafalgar y Justicia</em></p>
<p>Dibuja el diagrama de densidad de distribución de los diferentes precios. Serían 5 gráficas, una por cada barrio.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Diagrama de densidad necesita muchos puntos, así que tenemos que coger el precio de cada piso, no vale con el P.Medio</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>diagr_densidad <span class="ot">&lt;-</span> airbnb_entire[<span class="fu">which</span>(airbnb_entire<span class="sc">$</span>Barrio <span class="sc">==</span> <span class="st">'Recoletos'</span> <span class="sc">|</span> airbnb_entire<span class="sc">$</span>Barrio <span class="sc">==</span> <span class="st">'Goya'</span> <span class="sc">|</span> airbnb_entire<span class="sc">$</span>Barrio <span class="sc">==</span> <span class="st">'Sol'</span> <span class="sc">|</span> airbnb_entire<span class="sc">$</span>Barrio <span class="sc">==</span> <span class="st">'Trafalgar'</span> <span class="sc">|</span> airbnb_entire<span class="sc">$</span>Barrio <span class="sc">==</span> <span class="st">'Justicia'</span>),]</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Ahora sí, pintamos diagramas de densidad de distribución:</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(diagr_densidad, <span class="fu">aes</span>(<span class="at">x=</span>Precio, <span class="at">color=</span>Barrio)) <span class="sc">+</span> <span class="fu">geom_density</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 rows containing non-finite values (`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="PracticaFinal_Najli_Yaya_Estevez_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Calcula el tamaño medio, en metros cuadrados, para los 5 barrios anteriores y muéstralo en el mismo dataframe junto con el precio y número de entradas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>top5_100_m2 <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(diagr_densidad<span class="sc">$</span>MetrosCuadrados , <span class="fu">list</span>(diagr_densidad<span class="sc">$</span>Barrio), <span class="at">FUN=</span>mean, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(top5_100_m2) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Barrio"</span>, <span class="st">"M2Medios"</span>)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>top5_100_m2_precio <span class="ot">&lt;-</span> <span class="fu">merge</span>(top5_100_m2,top5_precio_100)</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>top5_100_m2_precio</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Barrio M2Medios CtdadPisos PrecioMedio
1      Goya 51.68504        142   111.33803
2  Justicia 28.52669        534    98.25468
3 Recoletos 26.66316        135   161.92537
4       Sol 45.61692        701   100.75036
5 Trafalgar 29.30426        223    98.57848</code></pre>
</div>
</div>
<p>Dibuja el diagrama de densidad de distribución de los diferentes tamaños de apartamentos. Serían 5 gráficas, una por cada barrio.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Diagrama de densidad necesita muchos puntos, así que tenemos que coger los m2 de cada piso, no vale con los m2 medios</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>diagr_densidad_2 <span class="ot">&lt;-</span> airbnb_entire[<span class="fu">which</span>(airbnb_entire<span class="sc">$</span>Barrio <span class="sc">==</span> <span class="st">'Recoletos'</span> <span class="sc">|</span> airbnb_entire<span class="sc">$</span>Barrio <span class="sc">==</span> <span class="st">'Goya'</span> <span class="sc">|</span> airbnb_entire<span class="sc">$</span>Barrio <span class="sc">==</span> <span class="st">'Sol'</span> <span class="sc">|</span> airbnb_entire<span class="sc">$</span>Barrio <span class="sc">==</span> <span class="st">'Trafalgar'</span> <span class="sc">|</span> airbnb_entire<span class="sc">$</span>Barrio <span class="sc">==</span> <span class="st">'Justicia'</span>),]</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Ahora sí, pintamos diagramas de densidad de distribución:</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(diagr_densidad_2, <span class="fu">aes</span>(<span class="at">x=</span>MetrosCuadrados, <span class="at">color=</span>Barrio)) <span class="sc">+</span> <span class="fu">geom_density</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1645 rows containing non-finite values (`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="PracticaFinal_Najli_Yaya_Estevez_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Esta claro que las medias de metros cuadrados de cada uno de estos 5 barrios parecen ser diferentes, pero ¿son estadísticamente diferentes? ¿Que test habría que usar para comprobarlo?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creamos subsets para cada barrio</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>airbnb_recoletos <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb_entire,Barrio<span class="sc">==</span><span class="st">"Recoletos"</span>)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>airbnb_goya <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb_entire,Barrio<span class="sc">==</span><span class="st">"Goya"</span>)</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>airbnb_justicia <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb_entire,Barrio<span class="sc">==</span><span class="st">"Justicia"</span>)</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>airbnb_trafalgar <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb_entire,Barrio<span class="sc">==</span><span class="st">"Trafalgar"</span>)</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>airbnb_sol <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb_entire,Barrio<span class="sc">==</span><span class="st">"Sol"</span>)</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Aplicamos Test de Shapiro para ver si siguen una distrb gaussiana</span></span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(airbnb_recoletos<span class="sc">$</span>MetrosCuadrados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  airbnb_recoletos$MetrosCuadrados
W = 0.75, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(airbnb_goya<span class="sc">$</span>MetrosCuadrados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  airbnb_goya$MetrosCuadrados
W = 0.93813, p-value = 0.5199</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(airbnb_justicia<span class="sc">$</span>MetrosCuadrados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  airbnb_justicia$MetrosCuadrados
W = 0.76212, p-value = 0.0006419</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(airbnb_trafalgar<span class="sc">$</span>MetrosCuadrados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  airbnb_trafalgar$MetrosCuadrados
W = 0.75023, p-value = 0.01276</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(airbnb_sol<span class="sc">$</span>MetrosCuadrados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  airbnb_sol$MetrosCuadrados
W = 0.83089, p-value = 8.691e-07</code></pre>
</div>
</div>
<p><em>Hipótesis H0 Shapiro: sigue distribución normal/gaussiana</em></p>
<p><em>Hipótesis H1 Shapiro: No sigue distribución normal/gaussiana</em></p>
<p><em>Parece que, en todo caso, el barrio de Goya puede estar siguiendo una distribución gaussiana.</em> <em>Uno parece seguir una gaussiana pero el resto seguro que no.</em></p>
<p><em>La hipótesis alternativa es que “No sigue una distribución gaussiana” y el pvalor inferior a 0.05 indica que debemos rechazar la hipótesis nula</em></p>
<p><em>Tenemos que elegir ahora el test para comparar las medias de m2 de cada barrio. Como no siguen distribución normal y son más de 3 grupos a comparar, usaremos Test de Kruskal-Wallis :</em> <em>kruskal.test( value ~ cl, data=df)</em></p>
<p><em>Hipótesis</em> <em>H0 Kruskal: Las medias de m2 de cada barrio son iguales, la diferencia de m2 medios NO es estadísticamente significativa</em></p>
<p><em>Hipótesis H1 Kruskal: La media de m2 por barrio NO son iguales entre sí, la diferencia de m2 medios es estadísticamente significativa</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(MetrosCuadrados <span class="sc">~</span> Barrio, airbnb_entire)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  MetrosCuadrados by Barrio
Kruskal-Wallis chi-squared = 78.411, df = 55, p-value = 0.02077</code></pre>
</div>
</div>
<p><em>p-valor &lt; 0.05 así que tenemos que descartar la hipótesis nula (H0) y diremos que la diferencia de m2 medios del apartamento según el barrio es estadísticamente significativa</em></p>
<p>Para únicamente los pisos de alquiler en el barrio de Sol:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>barrio_sol<span class="ot">&lt;-</span><span class="fu">subset</span>(airbnb_entire,Barrio<span class="sc">==</span><span class="st">"Sol"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>barrio_sol&lt;-subset(airbnb_entire,Barrio=="Sol")</code></p>
<p>El objetivo de esta parte es calcular un modelo lineal que combine alguna de estas variables: * NumBanyos * NumDormitorios * MaxOcupantes * MetrosCuadrados Pero primero calculamos la correlación para ver como se relacionan estas variables entre sí.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(barrio_sol[ , <span class="fu">c</span>(<span class="st">"NumBanyos"</span>, <span class="st">"NumDormitorios"</span>, <span class="st">"MaxOcupantes"</span>, <span class="st">"MetrosCuadrados"</span>)], <span class="at">use=</span><span class="st">"complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                NumBanyos NumDormitorios MaxOcupantes MetrosCuadrados
NumBanyos       1.0000000      0.6873719    0.7017290       0.4820549
NumDormitorios  0.6873719      1.0000000    0.7853809       0.5684521
MaxOcupantes    0.7017290      0.7853809    1.0000000       0.4286233
MetrosCuadrados 0.4820549      0.5684521    0.4286233       1.0000000</code></pre>
</div>
</div>
<p>Se observa que la correlación entre el número de dormitorios y los metros cuadrados es sorprendentemente baja. ¿Son de fiar esos números? Mediante un histograma o curvas de densidad podemos descartar números que no tienen sentido en el dataframe barrio_sol, para tener una matriz de correlación que tenga mayor sentido.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Pintamos histograma y curva de densidad:</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(barrio_sol, <span class="fu">aes</span>(<span class="at">x=</span>barrio_sol<span class="sc">$</span>MetrosCuadrados)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">fill=</span><span class="st">'darkgreen'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 641 rows containing non-finite values (`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="PracticaFinal_Najli_Yaya_Estevez_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(barrio_sol, <span class="fu">aes</span>(<span class="at">x=</span>barrio_sol<span class="sc">$</span>MetrosCuadrados)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">fill=</span><span class="st">'darkblue'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 641 rows containing non-finite values (`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="PracticaFinal_Najli_Yaya_Estevez_files/figure-html/unnamed-chunk-36-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>Efectivamente, hay muchos valores a 0 m2 o con superficies muy pequeñas como para ser apartamentos enteros habitables.</em></p>
<p>Una vez que hayamos filtrado los datos correspondientes, calcular el valor o la combinación de valores que mejor nos permite obtener el precio de un inmueble. Es decir, creamos el modelo lineal mencionado arriba.</p>
<p><em>Primero aplico el filtro &gt;&gt; Elimino entradas cuyos pisos tengan una superficie menor a 20 m2</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>barrio_sol_mod <span class="ot">&lt;-</span> barrio_sol[<span class="fu">which</span>(barrio_sol<span class="sc">$</span>MetrosCuadrados <span class="sc">&gt;</span> <span class="dv">20</span>),]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>Voy a comprobar que la correlación aumenta:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(barrio_sol_mod[ , <span class="fu">c</span>(<span class="st">"NumBanyos"</span>, <span class="st">"NumDormitorios"</span>, <span class="st">"MaxOcupantes"</span>, <span class="st">"MetrosCuadrados"</span>)], <span class="at">use=</span><span class="st">"complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                NumBanyos NumDormitorios MaxOcupantes MetrosCuadrados
NumBanyos       1.0000000      0.7245916    0.8604387       0.6040653
NumDormitorios  0.7245916      1.0000000    0.7854671       0.8290754
MaxOcupantes    0.8604387      0.7854671    1.0000000       0.6909450
MetrosCuadrados 0.6040653      0.8290754    0.6909450       1.0000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co">#OK, ha aumentado considerablemente!</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>Efectivamente antes la correlación entre nº de dormitorios y metros cuadrados era de 0.5684521 y ahora es de 0.8290754</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Ahora generamos un modelo para obtener el precio del inmueble</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>model_precio<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>barrio_sol_mod, <span class="at">formula =</span> Precio <span class="sc">~</span> NumBanyos <span class="sc">+</span> NumDormitorios <span class="sc">+</span> MetrosCuadrados <span class="sc">+</span> MaxOcupantes)</span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_precio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Precio ~ NumBanyos + NumDormitorios + MetrosCuadrados + 
    MaxOcupantes, data = barrio_sol_mod)

Residuals:
    Min      1Q  Median      3Q     Max 
-78.276 -15.432  -5.095  19.767  68.926 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)      31.2243    14.4988   2.154  0.04003 * 
NumBanyos         1.3061    15.1351   0.086  0.93185   
NumDormitorios   29.5746     9.1284   3.240  0.00308 **
MetrosCuadrados   0.1836     0.2225   0.825  0.41611   
MaxOcupantes      2.1814     4.6800   0.466  0.64474   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 32.23 on 28 degrees of freedom
Multiple R-squared:  0.7507,    Adjusted R-squared:  0.7151 
F-statistic: 21.08 on 4 and 28 DF,  p-value: 4.129e-08</code></pre>
</div>
</div>
<p>*Parece que NumDormitorios es la que mejor le va al Precio (tiene **)*</p>
<p>¿Que variable es más fiable para conocer el precio de un inmueble, el número de habitaciones o los metros cuadrados?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model_precio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      2.5 %    97.5 %
(Intercept)       1.5248915 60.923742
NumBanyos       -29.6967366 32.308878
NumDormitorios   10.8758819 48.273410
MetrosCuadrados  -0.2720613  0.639301
MaxOcupantes     -7.4051187 11.767978</code></pre>
</div>
</div>
<p><em>Para la variable metroscuadrados, el intervalo de confianza va de números negativos a positivos, esto significa que R no sabe decirnos</em> <em>Sin embargo, para el número de dormitorios, nos da un intervalo real aunque amplio</em></p>
<p><em>Así que es más fiable, para conocer el precio del inmueble, considerar el número de dormitorios</em></p>
<p>Responde con su correspondiente margen de error del 95%, ¿cuantos euros incrementa el precio del alquiler por cada metro cuadrado extra del piso?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>model_precio_m2<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>barrio_sol_mod, <span class="at">formula =</span> Precio <span class="sc">~</span> MetrosCuadrados)</span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_precio_m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Precio ~ MetrosCuadrados, data = barrio_sol_mod)

Residuals:
    Min      1Q  Median      3Q     Max 
-65.388 -21.792  -0.115  10.642 121.693 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      29.5861    14.1142   2.096   0.0443 *  
MetrosCuadrados   0.9912     0.1520   6.521 2.81e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 39.83 on 31 degrees of freedom
Multiple R-squared:  0.5784,    Adjusted R-squared:  0.5648 
F-statistic: 42.53 on 1 and 31 DF,  p-value: 2.809e-07</code></pre>
</div>
</div>
<p><em>Aumenta en 0.9912 el precio por cada m2</em></p>
<p><em>Muestro el intervalo de confianza:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model_precio_m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    2.5 %   97.5 %
(Intercept)     0.7999527 58.37229
MetrosCuadrados 0.6812218  1.30121</code></pre>
</div>
</div>
<p>Responde con su correspondiente margen de error del 95%, ¿cuantos euros incrementa el precio del alquiler por cada habitación?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>model_precio_hab<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>barrio_sol_mod, <span class="at">formula =</span> Precio <span class="sc">~</span> NumDormitorios)</span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_precio_hab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Precio ~ NumDormitorios, data = barrio_sol_mod)

Residuals:
    Min      1Q  Median      3Q     Max 
-89.214 -17.652  -5.652  18.457  61.786 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      43.762      8.919   4.907 2.80e-05 ***
NumDormitorios   38.890      4.156   9.359 1.52e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 31.37 on 31 degrees of freedom
Multiple R-squared:  0.7386,    Adjusted R-squared:  0.7302 
F-statistic: 87.58 on 1 and 31 DF,  p-value: 1.523e-10</code></pre>
</div>
</div>
<p><em>El precio aumenta en 38.890 por cada habitación</em></p>
<p><em>Muestro el intervalo de confianza:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model_precio_hab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %   97.5 %
(Intercept)    25.57224 61.95116
NumDormitorios 30.41513 47.36572</code></pre>
</div>
</div>
<p>¿Cual es la probabilidad de encontrar, en el barrio de Sol, un apartamento en alquiler con 3 dormitorios? ¿Cual es el intervalo de confianza de esa probabilidad?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Considerando todo el dataframe:</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>bt_sol <span class="ot">&lt;-</span> <span class="fu">binom.test</span>(<span class="fu">nrow</span>(barrio_sol[<span class="fu">which</span>(barrio_sol<span class="sc">$</span>NumDormitorios<span class="sc">==</span><span class="dv">3</span>),]), <span class="fu">nrow</span>(barrio_sol))</span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a>bt_sol</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  nrow(barrio_sol[which(barrio_sol$NumDormitorios == 3), ]) and nrow(barrio_sol)
number of successes = 55, number of trials = 701, p-value &lt; 2.2e-16
alternative hypothesis: true probability of success is not equal to 0.5
95 percent confidence interval:
 0.0596506 0.1009033
sample estimates:
probability of success 
            0.07845934 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Si solo consideramos pisos con m2 &gt; 20:</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>bt_sol_mod <span class="ot">&lt;-</span> <span class="fu">binom.test</span>(<span class="fu">nrow</span>(barrio_sol_mod[<span class="fu">which</span>(barrio_sol_mod<span class="sc">$</span>NumDormitorios<span class="sc">==</span><span class="dv">3</span>),]), <span class="fu">nrow</span>(barrio_sol_mod))</span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a>bt_sol_mod</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  nrow(barrio_sol_mod[which(barrio_sol_mod$NumDormitorios == 3), ]) and nrow(barrio_sol_mod)
number of successes = 3, number of trials = 33, p-value = 1.401e-06
alternative hypothesis: true probability of success is not equal to 0.5
95 percent confidence interval:
 0.01915494 0.24331635
sample estimates:
probability of success 
            0.09090909 </code></pre>
</div>
</div>
<p><em>En el caso de pisos completos en el barrio de Sol, la probabilidad de que tengan 3 habitaciones es de 0.07845934, con un intervalo de confianza del 95%.</em></p>
<p><em>Si nos centramos en los pisos con m2 &gt; 20, la probabilidad es de 0.09090909, con un intervalo de confianza del 95%.</em></p>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>